apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/project-codeflare/appwrapper/releases/download/v1.1.0/install.yaml

patches:
- path: patch-clusterrole-appwrapper.yaml
- path: patch-validatingwebhook-appwrapper.yaml
