apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/kueue/releases/download/v0.11.0/manifests.yaml
- https://github.com/project-codeflare/appwrapper/releases/download/v1.1.0/install.yaml
- github.com/ray-project/kuberay/ray-operator/config/default?ref=v1.3.0

patches:
- path: patch-clusterrole-appwrapper.yaml
- path: patch-validatingwebhook-appwrapper.yaml
- path: patch-configmap-kueue.yaml
