apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: appwrapper
    control-plane: controller-manager
  name: appwrapper-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: appwrapper-webhook-service
      namespace: appwrapper-system
      path: /validate-workload-codeflare-dev-v1beta2-appwrapper
  failurePolicy: Fail
  name: vappwrapper.kb.io
  rules:
  - apiGroups:
    - workload.codeflare.dev
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    resources:
    - appwrappers
  sideEffects: None