version: "2"
run:
  allow-parallel-runners: true

linters:
  enable:
  - copyloopvar
  - dupl
  - ginkgolinter
  - goconst
  - gocyclo
  - goheader
  - lll
  - misspell
  - nakedret
  - unconvert
  - unparam

linters-settings:
  goheader:
    template-path: .copyright-template
  lll:
    line-length: 500

issues:
  fix: true
  exclude-rules:
  - linters:
    - lll
    path: apis/*
  - linters:
    - dupl
    - lll
    path: internal/*
  - linters:
    - lll
    path: pkg/*
  exclude-dirs:
  - python
  - third_party
  - builtin
  - examples
