apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: appwrapper
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./kustomization/appwrapper"
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
  - name: cert-manager
