apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kuberay
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
  path: "./kustomization/kuberay"
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
  - name: cert-manager
