apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
  - name: cert-manager
  - name: kueue
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
    namespace: flux-system
  path: "./automation/flux/helm/loki"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
  - name: loki
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
    namespace: flux-system
  path: "./automation/flux/helm/promtail"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
  - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
    namespace: flux-system
  path: "./automation/flux/helm/kube-state-metrics"
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: event-exporter
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
  - name: loki
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
    namespace: flux-system
  path: "./automation/kustomization/event-exporter"
  prune: true