apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-test-storage
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
  path: "./automation/flux/helm/nfs-storage"
  prune: true
  wait: true
  timeout: 5m
