{{- if .Values.webhooks.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ printf "%s-job-mutating" .Release.Name }}
  labels:
    {{- include "kaiwo.labels" . | nindent 4 }}
  annotations:
    # Let cert-manager inject the CA bundle into this webhook configuration
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-serving-cert" .Release.Namespace .Release.Name }}
webhooks:
  - name: mutate-jobs.kaiwo.silogen.ai
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ printf "%s-webhook-service" .Release.Name }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate-batch-v1-job"
    rules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["jobs"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5
    matchPolicy: Equivalent
    reinvocationPolicy: Never
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ printf "%s-job-validating" .Release.Name }}
  labels:
    {{- include "kaiwo.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-serving-cert" .Release.Namespace .Release.Name }}
webhooks:
  - name: validate-jobs.kaiwo.silogen.ai
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ printf "%s-webhook-service" .Release.Name }}
        namespace: {{ .Release.Namespace }}
        path: "/validate-batch-v1-job"
    rules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE","DELETE"]
        resources: ["jobs"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5
    matchPolicy: Equivalent
{{- end }}
