apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: job-mutating
webhooks:
  - name: mutate-jobs.kaiwo.silogen.ai
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: webhook-service
        namespace: kaiwo-system
        path: "/mutate-batch-v1-job"
    rules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5
    matchPolicy: Equivalent
    reinvocationPolicy: Never

---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: job-validating
webhooks:
  - name: validate-jobs.kaiwo.silogen.ai
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: webhook-service
        namespace: kaiwo-system
        path: "/validate-batch-v1-job"
    rules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5
    matchPolicy: Equivalent
