apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rocm
  namespace: flux-system
spec:
  interval: 24h
  url: https://rocm.github.io/gpu-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-ganesha
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
