apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kaiwo-job-mutating
webhooks:
  - name: mutate-jobs.kaiwo.silogen.ai
    admissionReviewVersions: ["v1"]
    clientConfig:
      url: "https://172.17.0.1:9443/mutate-batch-v1-job"
      caBundle: overwriteme
    rules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5
    matchPolicy: Equivalent
    reinvocationPolicy: Never

---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kaiwo-job-validating
webhooks:
  - name: validate-jobs.kaiwo.silogen.ai
    admissionReviewVersions: ["v1"]
    clientConfig:
      url: "https://172.17.0.1:9443/validate-batch-v1-job"
      caBundle: overwriteme
    rules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["jobs"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5
    matchPolicy: Equivalent
