apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: github-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
#- apiGroups: ["networking.k8s.io"]
#  resources: ["*"]
#  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
#- apiGroups: ["argoproj.io"]
#  resources: ["*"]
#  verbs: ["*"]
#- apiGroups: ["helm.toolkit.fluxcd.io"]
#  resources: ["*"]
#  verbs: ["*"]
#- apiGroups: ["kustomize.toolkit.fluxcd.io"]
#  resources: ["*"]
#  verbs: ["*"]
#- apiGroups: ["source.toolkit.fluxcd.io"]
#  resources: ["*"]
#  verbs: ["*"]
- apiGroups: ["kueue.x-k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["ray.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["workload.codeflare.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["kaiwo.silogen.ai"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["config.kaiwo.silogen.ai"]
  resources: ["*"]
  verbs: ["*"]
#- apiGroups: ["kubeflow.org"]
#  resources: ["*"]
#  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-runner
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: github-runners
