apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: gpu-runners
  namespace: github-runners
spec:
  githubConfigUrl: "https://github.com/silogen/kaiwo"
  githubConfigSecret: github-auth-secret
  minRunners: 0
  maxRunners: 10
  runnerGroup: "gpu-cluster"
  runnerScaleSetName: "gpu-runners"
  template:
    spec:
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: RUNNER_FEATURE_FLAG_ONCE
          value: "true"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            amd.com/gpu: "1"
          limits:
            memory: "8Gi"
            cpu: "4"
            amd.com/gpu: "1"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: work
          mountPath: /home/runner/_work
        securityContext:
          privileged: true
      - name: dind
        image: docker:24-dind
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_DRIVER
          value: overlay2
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: work
          mountPath: /home/runner/_work
      serviceAccountName: github-runner
      restartPolicy: Never
      volumes:
      - name: docker-sock
        emptyDir: {}
      - name: work
        emptyDir: {}
