apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: kaiwo
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory", "amd.com/gpu"]
    flavors:
    - name: base-gpu-flavour
      resources:
      - name: "cpu"
        nominalQuota: 400
      - name: "memory"
        nominalQuota: 1800Gi
      - name: "amd.com/gpu"
        nominalQuota: 16
