# This rule is not used by the project kaiwo itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kaiwo.silogen.ai resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kaiwo
    app.kubernetes.io/managed-by: kustomize
  name: kaiwoservice-viewer-role
rules:
- apiGroups:
  - kaiwo.silogen.ai
  resources:
  - kaiwoservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kaiwo.silogen.ai
  resources:
  - kaiwoservices/status
  verbs:
  - get
