//go:build !ignore_autogenerated

// Copyright (c) 2025 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoConfig) DeepCopyInto(out *KaiwoConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoConfig.
func (in *KaiwoConfig) DeepCopy() *KaiwoConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KaiwoConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoConfigList) DeepCopyInto(out *KaiwoConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KaiwoConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoConfigList.
func (in *KaiwoConfigList) DeepCopy() *KaiwoConfigList {
	if in == nil {
		return nil
	}
	out := new(KaiwoConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KaiwoConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoConfigSpec) DeepCopyInto(out *KaiwoConfigSpec) {
	*out = *in
	out.Ray = in.Ray
	out.Storage = in.Storage
	out.Nodes = in.Nodes
	out.Scheduling = in.Scheduling
	in.ResourceMonitoring.DeepCopyInto(&out.ResourceMonitoring)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoConfigSpec.
func (in *KaiwoConfigSpec) DeepCopy() *KaiwoConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KaiwoConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoNodeConfig) DeepCopyInto(out *KaiwoNodeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoNodeConfig.
func (in *KaiwoNodeConfig) DeepCopy() *KaiwoNodeConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoRayConfig) DeepCopyInto(out *KaiwoRayConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoRayConfig.
func (in *KaiwoRayConfig) DeepCopy() *KaiwoRayConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoRayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoResourceMonitoringConfig) DeepCopyInto(out *KaiwoResourceMonitoringConfig) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoResourceMonitoringConfig.
func (in *KaiwoResourceMonitoringConfig) DeepCopy() *KaiwoResourceMonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoResourceMonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoSchedulingConfig) DeepCopyInto(out *KaiwoSchedulingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoSchedulingConfig.
func (in *KaiwoSchedulingConfig) DeepCopy() *KaiwoSchedulingConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoSchedulingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoStorageConfig) DeepCopyInto(out *KaiwoStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoStorageConfig.
func (in *KaiwoStorageConfig) DeepCopy() *KaiwoStorageConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoStorageConfig)
	in.DeepCopyInto(out)
	return out
}
