//go:build !ignore_autogenerated

// Copyright (c) 2025 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMAzureBlobCredential) DeepCopyInto(out *AIMAzureBlobCredential) {
	*out = *in
	out.ConnectionString = in.ConnectionString
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMAzureBlobCredential.
func (in *AIMAzureBlobCredential) DeepCopy() *AIMAzureBlobCredential {
	if in == nil {
		return nil
	}
	out := new(AIMAzureBlobCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMGCSCredential) DeepCopyInto(out *AIMGCSCredential) {
	*out = *in
	out.ApplicationCredentials = in.ApplicationCredentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMGCSCredential.
func (in *AIMGCSCredential) DeepCopy() *AIMGCSCredential {
	if in == nil {
		return nil
	}
	out := new(AIMGCSCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMNamespaceConfigSpec) DeepCopyInto(out *AIMNamespaceConfigSpec) {
	*out = *in
	out.Gateway = in.Gateway
	in.Credentials.DeepCopyInto(&out.Credentials)
	in.Images.DeepCopyInto(&out.Images)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMNamespaceConfigSpec.
func (in *AIMNamespaceConfigSpec) DeepCopy() *AIMNamespaceConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AIMNamespaceConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMNamespaceCredentials) DeepCopyInto(out *AIMNamespaceCredentials) {
	*out = *in
	if in.HuggingFaceToken != nil {
		in, out := &in.HuggingFaceToken, &out.HuggingFaceToken
		*out = new(SecretValueReference)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = make([]AIMS3Credential, len(*in))
		copy(*out, *in)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = make([]AIMGCSCredential, len(*in))
		copy(*out, *in)
	}
	if in.AzureBlob != nil {
		in, out := &in.AzureBlob, &out.AzureBlob
		*out = make([]AIMAzureBlobCredential, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMNamespaceCredentials.
func (in *AIMNamespaceCredentials) DeepCopy() *AIMNamespaceCredentials {
	if in == nil {
		return nil
	}
	out := new(AIMNamespaceCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMNamespaceImageConfig) DeepCopyInto(out *AIMNamespaceImageConfig) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMNamespaceImageConfig.
func (in *AIMNamespaceImageConfig) DeepCopy() *AIMNamespaceImageConfig {
	if in == nil {
		return nil
	}
	out := new(AIMNamespaceImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMS3Credential) DeepCopyInto(out *AIMS3Credential) {
	*out = *in
	out.AccessKeyId = in.AccessKeyId
	out.SecretAccessKey = in.SecretAccessKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMS3Credential.
func (in *AIMS3Credential) DeepCopy() *AIMS3Credential {
	if in == nil {
		return nil
	}
	out := new(AIMS3Credential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRef) DeepCopyInto(out *GatewayRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRef.
func (in *GatewayRef) DeepCopy() *GatewayRef {
	if in == nil {
		return nil
	}
	out := new(GatewayRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoConfig) DeepCopyInto(out *KaiwoConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoConfig.
func (in *KaiwoConfig) DeepCopy() *KaiwoConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KaiwoConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoConfigList) DeepCopyInto(out *KaiwoConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KaiwoConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoConfigList.
func (in *KaiwoConfigList) DeepCopy() *KaiwoConfigList {
	if in == nil {
		return nil
	}
	out := new(KaiwoConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KaiwoConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoConfigSpec) DeepCopyInto(out *KaiwoConfigSpec) {
	*out = *in
	out.Ray = in.Ray
	out.Storage = in.Storage
	out.Nodes = in.Nodes
	out.Scheduling = in.Scheduling
	in.ResourceMonitoring.DeepCopyInto(&out.ResourceMonitoring)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoConfigSpec.
func (in *KaiwoConfigSpec) DeepCopy() *KaiwoConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KaiwoConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoNodeConfig) DeepCopyInto(out *KaiwoNodeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoNodeConfig.
func (in *KaiwoNodeConfig) DeepCopy() *KaiwoNodeConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoRayConfig) DeepCopyInto(out *KaiwoRayConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoRayConfig.
func (in *KaiwoRayConfig) DeepCopy() *KaiwoRayConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoRayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoResourceMonitoringConfig) DeepCopyInto(out *KaiwoResourceMonitoringConfig) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoResourceMonitoringConfig.
func (in *KaiwoResourceMonitoringConfig) DeepCopy() *KaiwoResourceMonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoResourceMonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoSchedulingConfig) DeepCopyInto(out *KaiwoSchedulingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoSchedulingConfig.
func (in *KaiwoSchedulingConfig) DeepCopy() *KaiwoSchedulingConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoSchedulingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoStorageConfig) DeepCopyInto(out *KaiwoStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoStorageConfig.
func (in *KaiwoStorageConfig) DeepCopy() *KaiwoStorageConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretValueReference) DeepCopyInto(out *SecretValueReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretValueReference.
func (in *SecretValueReference) DeepCopy() *SecretValueReference {
	if in == nil {
		return nil
	}
	out := new(SecretValueReference)
	in.DeepCopyInto(out)
	return out
}
