//go:build !ignore_autogenerated

// Copyright 2025 Advanced Micro Devices, Inc.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoConfig) DeepCopyInto(out *KaiwoConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoConfig.
func (in *KaiwoConfig) DeepCopy() *KaiwoConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KaiwoConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoConfigList) DeepCopyInto(out *KaiwoConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KaiwoConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoConfigList.
func (in *KaiwoConfigList) DeepCopy() *KaiwoConfigList {
	if in == nil {
		return nil
	}
	out := new(KaiwoConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KaiwoConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoConfigSpec) DeepCopyInto(out *KaiwoConfigSpec) {
	*out = *in
	out.Ray = in.Ray
	out.Storage = in.Storage
	out.Nodes = in.Nodes
	out.Scheduling = in.Scheduling
	in.ResourceMonitoring.DeepCopyInto(&out.ResourceMonitoring)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoConfigSpec.
func (in *KaiwoConfigSpec) DeepCopy() *KaiwoConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KaiwoConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoNodeConfig) DeepCopyInto(out *KaiwoNodeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoNodeConfig.
func (in *KaiwoNodeConfig) DeepCopy() *KaiwoNodeConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoRayConfig) DeepCopyInto(out *KaiwoRayConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoRayConfig.
func (in *KaiwoRayConfig) DeepCopy() *KaiwoRayConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoRayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoResourceMonitoringConfig) DeepCopyInto(out *KaiwoResourceMonitoringConfig) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoResourceMonitoringConfig.
func (in *KaiwoResourceMonitoringConfig) DeepCopy() *KaiwoResourceMonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoResourceMonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoSchedulingConfig) DeepCopyInto(out *KaiwoSchedulingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoSchedulingConfig.
func (in *KaiwoSchedulingConfig) DeepCopy() *KaiwoSchedulingConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoSchedulingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KaiwoStorageConfig) DeepCopyInto(out *KaiwoStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KaiwoStorageConfig.
func (in *KaiwoStorageConfig) DeepCopy() *KaiwoStorageConfig {
	if in == nil {
		return nil
	}
	out := new(KaiwoStorageConfig)
	in.DeepCopyInto(out)
	return out
}
