apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
  - name: loki
  chart:
    spec:
      chart: promtail
      version: "6.15.5"  # Latest stable version
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  targetNamespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Promtail configuration
    config:
      # Send logs to Loki
      clients:
      - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
        tenant_id: ""
      
      # Positions file for tracking log progress
      positions:
        filename: /tmp/positions.yaml
      
      # Server configuration
      server:
        http_listen_port: 3101
        grpc_listen_port: 9095
      
      # Scrape configurations for different log sources
      scrape_configs:
      # Container logs
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
        - role: pod
        pipeline_stages:
        - cri: {}
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_controller_name
          regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
          action: replace
          target_label: __tmp_controller_name
        - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
          - __tmp_controller_name
          - __meta_kubernetes_pod_name
          regex: ^;*([^;]+)(;.*)?$
          action: replace
          target_label: app
        - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_instance
          - __meta_kubernetes_pod_label_instance
          regex: ^;*([^;]+)(;.*)?$
          action: replace
          target_label: instance
        - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_component
          - __meta_kubernetes_pod_label_component
          regex: ^;*([^;]+)(;.*)?$
          action: replace
          target_label: component
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: node_name
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container
        - action: replace
          replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
        - action: replace
          regex: true/(.*)
          replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      
      # System logs
      - job_name: kubernetes-pods-static
        kubernetes_sd_configs:
        - role: pod
        pipeline_stages:
        - cri: {}
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          action: drop
          regex: ""
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_label_component
          target_label: __tmp_component
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: node_name
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container
        - action: replace
          replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          - __meta_kubernetes_pod_container_name
          target_label: __path__
    
    # Resources
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    
    # Run as DaemonSet to collect logs from all nodes
    daemonset:
      enabled: true
    
    # Security context
    securityContext:
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsUser: 0
    
    # Volumes for log access
    extraVolumes:
    - name: pods
      hostPath:
        path: /var/log/pods
    - name: containers
      hostPath:
        path: /var/lib/docker/containers
    
    extraVolumeMounts:
    - name: pods
      mountPath: /var/log/pods
      readOnly: true
    - name: containers
      mountPath: /var/lib/docker/containers
      readOnly: true
    
    # ServiceMonitor for monitoring Promtail itself
    serviceMonitor:
      enabled: false  # Disable for now