apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels:
    kaiwo.silogen.ai/managed: "true"
spec:
  template:
    spec:
      containers:
        - name: hello-world
          image: ubuntu:latest
          imagePullPolicy: Always
          # Just spin & wait forever
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 5; done;" ]
      restartPolicy: Never
      
