repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  # Grafana Loki - Log aggregation
  - name: loki
    namespace: test-observability
    createNamespace: true
    chart: grafana/loki
    version: 6.23.0
    values:
      - deploymentMode: SingleBinary
        # Explicitly disable other deployment modes
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          limits_config:
            retention_period: 720h  # 30 days
            max_query_series: 100000
            max_query_lookback: 720h
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: openebs-hostpath
            size: 50Gi
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        gateway:
          enabled: false  # Disabled - using direct Loki access instead
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
        test:
          enabled: false

  # Grafana - Visualization and dashboards
  - name: grafana
    namespace: test-observability
    chart: grafana/grafana
    version: 10.1.4
    values:
      - adminPassword: admin  # Change this in production!
        persistence:
          enabled: true
          storageClassName: openebs-hostpath
          size: 10Gi
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        # Disable init container - PVC already has correct permissions
        initChownData:
          enabled: false
        # Enable sidecar to auto-reload dashboards and datasources
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            labelValue: "1"
            folder: /tmp/dashboards
            defaultFolderName: KAIWO
            searchNamespace: test-observability
          datasources:
            enabled: false  # We configure datasources statically
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                uid: loki
                url: http://loki-0.loki-headless.test-observability.svc.cluster.local:3100
                access: proxy
                isDefault: false
                jsonData:
                  maxLines: 1000
              - name: Prometheus
                type: prometheus
                uid: prometheus
                url: http://kps-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
                access: proxy
                isDefault: true
                jsonData:
                  httpMethod: POST
                  timeInterval: 30s
        # Pre-configure dashboards
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
              - name: 'kaiwo'
                orgId: 1
                folder: 'KAIWO Observability'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/kaiwo
        dashboardsConfigMaps:
          kaiwo: grafana-dashboards-kaiwo
        service:
          type: NodePort
          nodePort: 30300

  # Grafana Alloy - Telemetry collector for host cluster
  - name: alloy-host
    namespace: test-observability
    chart: grafana/alloy
    version: 0.12.0
    values:
      - alloy:
          configMap:
            name: alloy-host-config
            create: false  # We'll create this separately
          clustering:
            enabled: false
        controller:
          type: daemonset
          tolerations:
            - effect: NoSchedule
              operator: Exists
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
