# Filter: Exclude Fluent Bit's own logs to prevent recursive capture
# Named to run early (alphabetically before kubernetes filter)
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: aaa-exclude-fluent-bit
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  filters:
    - grep:
        exclude: kubernetes_labels_app_kubernetes_io_name fluent-bit
