# Simple test: Filter by namespace and output to stdout
# NOTE: ClusterFilters execute by ordinal value (lower = earlier)
# Default filters have ordinals: containerd(0), kubernetes(0), systemd(0), nest/modify(0)
# We need our grep filters to run AFTER kubernetes enrichment adds metadata
# So we use ordinal: 100

---
# ConfigMap: Lua scripts for log processing
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-lua-scripts
  namespace: test-observability
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
data:
  extract-namespace-fields.lua: |
    -- Extract installer, run_id, run_attempt from namespace name
    -- Pattern: test-{installer}-{run-id}-{run-attempt}
    -- Example: test-ci-550e8400-e29b-41d4-a89f-446657440000-1
    function extract_namespace_fields(tag, timestamp, record)
        local namespace = record["kubernetes"]["namespace_name"]

        if namespace then
            -- Pattern: test-{installer}-{run-id}-{run-attempt}
            local installer, run_id, run_attempt = string.match(namespace, "^test%-([^%-]+)%-(.+)%-(%d+)$")

            if installer and run_id and run_attempt then
                record["installer"] = installer
                record["run_id"] = run_id
                record["run_attempt"] = run_attempt
            end
        end

        return 2, timestamp, record
    end

  classify-log-type.lua: |
    -- Classify logs into three types: audit, event, or pod
    -- Uses pod labels for classification
    function classify_log_type(tag, timestamp, record)
        local kubernetes = record["kubernetes"]
        if not kubernetes then
            record["log_type"] = "pod"
            return 2, timestamp, record
        end

        local labels = kubernetes["labels"]
        local app_label = labels and labels["app"] or nil

        -- Type 1: Audit logs (vCluster pods have app=vcluster label)
        if app_label == "vcluster" then
            record["log_type"] = "audit"
            return 2, timestamp, record
        end

        -- Type 2: Kubernetes Events (event-exporter pods have app=event-exporter label)
        if app_label == "event-exporter" then
            record["log_type"] = "event"
            return 2, timestamp, record
        end

        -- Type 3: Pod logs (everything else)
        record["log_type"] = "pod"

        return 2, timestamp, record
    end

---
# Filter: Exclude test-observability namespace (runs after nest lift adds kubernetes_ prefix)
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: exclude-test-observability
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  ordinal: 100
  filters:
    - grep:
        exclude: "$kubernetes['namespace_name'] test-observability"

---
# Filter: Only keep logs from namespaces matching test-{installer}-{run-id}-{run-attempt}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: include-test-namespace
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  ordinal: 101
  filters:
    - grep:
        # Match namespaces with pattern: test-{installer}-{run-id}-{run-attempt}
        # Using record accessor syntax to access nested kubernetes.namespace_name field
        regex: "$kubernetes['namespace_name'] ^test-[^-]+-.*-\\d+$"

---
# Filter: Extract installer, run_id, run_attempt using Lua script
# Runs at ordinal 102 - after all default filters complete
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: extract-namespace-fields
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  ordinal: 102
  filters:
    - lua:
        script:
          key: extract-namespace-fields.lua
          name: fluent-bit-lua-scripts
        call: extract_namespace_fields

---
# Filter: Classify log type (audit, event, or pod)
# Runs at ordinal 103 - after namespace fields are extracted
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: classify-log-type
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  ordinal: 103
  filters:
    - lua:
        script:
          key: classify-log-type.lua
          name: fluent-bit-lua-scripts
        call: classify_log_type

---
# Output: Stdout
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: stdout-test
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  stdout: {}
