apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
  - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
    namespace: flux-system
  path: "./dependencies/dev/base/monitoring"
  prune: true
  targetNamespace: monitoring
