apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      version: 6.6.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 10m  # Increase timeout
  interval: 30m
  targetNamespace: monitoring
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      schemaConfig:
        configs:
        - from: "2024-04-01"
          index:
            period: 24h
            prefix: loki_index_
          object_store: filesystem
          schema: v13
          store: tsdb
    singleBinary:
      replicas: 1
      persistence:
        enabled: false
      extraVolumes:
        - name: storage
          emptyDir: {}
      extraVolumeMounts:
        - name: storage
          mountPath: /var/loki
    test:
      enabled: false
    backend:
      replicas: 0
    write:
      replicas: 0
    read:
      replicas: 0
    gateway:
      enabled: false
