apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: nfs-server-provisioner
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: nfs-ganesha
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  targetNamespace: storage
  values:
    persistence:
      enabled: false
    storageClass:
      create: true
      name: rwx-nfs
