apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fake-gpu-setup
  namespace: flux-system
spec:
  interval: 10m
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
    namespace: flux-system
  path: "./automation/kustomization/nvidia-fake-gpu"
  prune: true
  postBuild:
    substitute:
      CLUSTER_TYPE: "kind"
  healthChecks:
  - apiVersion: apps/v1
    kind: DaemonSet
    name: device-plugin
    namespace: gpu-operator
  - apiVersion: apps/v1
    kind: DaemonSet
    name: nvidia-dcgm-exporter
    namespace: gpu-operator