# Filter: Extract installer, run_id, run_attempt from namespace name
# Uses Lua script to parse namespace name and add fields to each log record
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: extract-namespace-fields
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  ordinal: 120
  filters:
    - lua:
        script:
          key: extract-namespace-fields.lua
          name: fluent-bit-lua-scripts
        call: extract_namespace_fields
