# Filter: Classify logs into three types: audit, event, or pod
# Uses pod labels (app=vcluster, app=event-exporter) for classification
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: classify-log-type
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  match: kube.*
  ordinal: 130
  filters:
    - lua:
        script:
          key: classify-log-type.lua
          name: fluent-bit-lua-scripts
        call: classify_log_type
