apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-runner-scale-set
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  targetNamespace: github-runners
  dependsOn:
  - name: actions-runner-controller
    namespace: flux-system
  values:
    runnerScaleSetName: "gpu-runners"
    githubConfigUrl: "https://github.com/silogen/kaiwo"
    githubConfigSecret: "github-auth-secret"
    minRunners: 0
    maxRunners: 1
    containerMode:
      type: "dind"
    template:
      spec:
        serviceAccountName: github-runner
        containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          env:
          - name: RUNNER_FEATURE_FLAG_ONCE
            value: "true"
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
              amd.com/gpu: "1"
            limits:
              memory: "8Gi"
              cpu: "4"
              amd.com/gpu: "1"
          securityContext:
            runAsUser: 1001
            runAsGroup: 121
        restartPolicy: Never
