---
# Simple Alloy deployment in host cluster vCluster namespace to receive audit logs
# This runs alongside the vCluster pod and forwards audit logs to Loki
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-audit-receiver-config
  namespace: ${VCLUSTER_NAMESPACE}
data:
  config.alloy: |
    // Remote write to Loki in monitoring namespace
    loki.write "host_loki" {
      endpoint {
        url = "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
      }
      external_labels = {
        cluster = "vcluster",
        vcluster_namespace = env("VCLUSTER_NAMESPACE"),
        github_run_id = env("GITHUB_RUN_ID"),
        github_run_attempt = env("GITHUB_RUN_ATTEMPT"),
        installer = env("INSTALLER"),
        log_type = "k8s_audit_log",
      }
    }

    // Webhook receiver for audit logs
    loki.source.webhook "audit_logs" {
      http {
        listen_address = "0.0.0.0"
        listen_port    = 8080
      }
      forward_to = [loki.process.audit_logs.receiver]
    }

    // Process audit logs
    loki.process "audit_logs" {
      forward_to = [loki.write.host_loki.receiver]

      // Parse audit log JSON
      stage.json {
        expressions = {
          verb             = "verb",
          user             = "user.username",
          namespace        = "objectRef.namespace",
          resource         = "objectRef.resource",
          name             = "objectRef.name",
          stage            = "stage",
          status_code      = "responseStatus.code",
          request_uri      = "requestURI",
        }
      }

      // Add labels from audit log fields
      stage.labels {
        values = {
          verb      = "",
          namespace = "",
          resource  = "",
          stage     = "",
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: alloy-audit-receiver
  namespace: ${VCLUSTER_NAMESPACE}
  labels:
    app: alloy-audit-receiver
spec:
  type: ClusterIP
  ports:
    - name: audit-webhook
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: alloy-audit-receiver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy-audit-receiver
  namespace: ${VCLUSTER_NAMESPACE}
  labels:
    app: alloy-audit-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy-audit-receiver
  template:
    metadata:
      labels:
        app: alloy-audit-receiver
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 473  # Alloy user
        fsGroup: 473    # Ensure volumes are writable by alloy user
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: alloy
          image: grafana/alloy:v1.5.1
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
          env:
            - name: VCLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GITHUB_RUN_ID
              value: "${GITHUB_RUN_ID}"
            - name: GITHUB_RUN_ATTEMPT
              value: "${GITHUB_RUN_ATTEMPT}"
            - name: INSTALLER
              value: "${INSTALLER}"
          ports:
            - containerPort: 8080
              name: audit-webhook
            - containerPort: 12345
              name: http-metrics
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: data
              mountPath: /var/lib/alloy/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: alloy-audit-receiver-config
        - name: data
          emptyDir: {}
