---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-vcluster
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-vcluster
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
      - pods/log
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-vcluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy-vcluster
subjects:
  - kind: ServiceAccount
    name: alloy-vcluster
    namespace: ${NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:
  name: alloy-vcluster
  namespace: ${NAMESPACE}
  labels:
    app: alloy-vcluster
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 12345
      targetPort: 12345
      protocol: TCP
  selector:
    app: alloy-vcluster
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy-vcluster
  namespace: ${NAMESPACE}
  labels:
    app: alloy-vcluster
spec:
  selector:
    matchLabels:
      app: alloy-vcluster
  template:
    metadata:
      labels:
        app: alloy-vcluster
    spec:
      serviceAccountName: alloy-vcluster
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        fsGroup: 473
        runAsUser: 473
        runAsNonRoot: true
      containers:
        - name: alloy
          image: grafana/alloy:v1.5.1
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VCLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GITHUB_RUN_ID
              value: "${GITHUB_RUN_ID}"
            - name: GITHUB_RUN_ATTEMPT
              value: "${GITHUB_RUN_ATTEMPT}"
            - name: INSTALLER
              value: "${INSTALLER}"
          ports:
            - containerPort: 12345
              name: http-metrics
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: data
              mountPath: /var/lib/alloy/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: alloy-vcluster-config
        - name: data
          emptyDir: {}
      tolerations:
        - effect: NoSchedule
          operator: Exists
