apiVersion: v1
kind: ConfigMap
metadata:
  name: vcluster-audit-webhook
  # This will be created in the vCluster namespace on the host cluster (e.g., alex-test)
data:
  webhook-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: alloy
        cluster:
          # Alloy runs in the same namespace as vCluster (host cluster)
          # Use localhost since API server and Alloy are in same pod/namespace
          server: http://alloy-audit-receiver:8080/audit
          # No TLS for simplicity - Alloy runs in same namespace
    contexts:
      - context:
          cluster: alloy
          user: ""
        name: default-context
    current-context: default-context
    preferences: {}
    users: []
