apiVersion: ray.io/v1
kind: RayService
metadata:
  name: vllm-distributed-inference-test
  # The `namespace` key will get overridden by the submit function
  namespace: av-test
spec:
  # The `serveConfigV2` key will get overridden by the submit function
  serveConfigV2: ""
  rayClusterConfig:
    enableInTreeAutoscaling: true
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        spec:
          containers:
            - name: ray-head
              image: ghcr.io/silogen/rocm-ray:v0.3
              env:
                - name: HUGGING_FACE_HUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: hf-token
                      key: hf-token
              resources:
                limits:
                  cpu: "10"
                  memory: "300Gi"
                  amd.com/gpu: "8"
                requests:
                  cpu: "10"
                  memory: "300Gi"
                  amd.com/gpu: "8"
              volumeMounts:
                - mountPath: /workload
                  name: app-mount
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
          volumes:
            - name: app-mount
              configMap:
                name: vllm-serve-example
                items:
                  - key: __init__.py
                    path: __init__.py
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 4
        groupName: gpu-group
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: llm
                image: ghcr.io/silogen/rocm-ray:v0.2
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                env:
                  - name: HUGGING_FACE_HUB_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: hf-token
                        key: hf-token
                # The `resources` key will get overridden by the submit function
                resources:
                  limits:
                    cpu: "10"
                    memory: "300Gi"
                    amd.com/gpu: "8"
                  requests:
                    cpu: "10"
                    memory: "300Gi"
                    amd.com/gpu: "8"
                volumeMounts:
                  - mountPath: /workload
                    name: app-mount
            volumes:
              - name: app-mount
                configMap:
                  name: vllm-serve-example
                  items:
                    - key: __init__.py
                      path: __init__.py
