apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/kueue/releases/download/v0.11.0/manifests.yaml

patches:
- path: patch-configmap-kueue.yaml
