apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
  path: "./automation/flux/helm/actions-runner-controller"
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
  - name: cert-manager
