apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: device-config
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./kustomization/amd-gpu-device-config"
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
  - name: amd-gpu-operator
