apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Base infrastructure
- ../base

# AMD GPU specific
#- amd-gpu-operator.yaml
- operator.yaml
- device-config.yaml
- monitoring.yaml
- github-runners.yaml
