apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: amd-gpu-operator
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: kaiwo-source
  path: "./automation/flux/helm/amd-gpu-operator"
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
  - name: cert-manager
